name: "Website Bug Report"
description: "Report any bugs about this website here!"
title: "[WEBSITE BUG]:"
labels: bug
body:
- type: markdown
  attributes:
    value: "# Welcome!"
- type: markdown
  attributes:
    value: |
      ### Thanks for wanting to fill out this form! This will help us very much in fixing bugs we dont know that exists.
- type: dropdown
  id: browser
  attributes:
    label: Which browser do you use?
    options:
      - Brave
      - Chrome
      - Opera
      - Opera GX
      - Microsoft Edge
      - Vivaldi
      - Firefox
      - Kiwi Browser
      - Safari
      - Arc Browser
      - Workona
      - Other Browser
  validations:
    required: true
- type: textarea
  id: bugtext
  attributes:
    label: Explain what the bug does here.
    description: "Text about bug here"
  validations:
    required: true
