name: "Website Bug Report"
description: "Report any bugs about this website here!"
body:
- type: markdown
  attributes:
    value: "# Welcome!"
- type: markdown
  attributes:
    value: |
      "### Thanks for wanting to fill out this form! This will help us very much in fixing bugs we dont know that exists."
